acttest2/config/routes.rb
Acttest2::Application.routes.draw do
  resources :lectures

  resources :courses

  resources :users

  root :to => 'courses#index'

end

acttest2/app/models/course.rb
class Course < ActiveRecord::Base
  has_many :lectures
  
  
end

acttest2/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  belongs_to :course
end

acttest2/app/models/user.rb
class User < ActiveRecord::Base
end

acttest2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

acttest2/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @course = Course.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/new
  # GET /courses/new.json
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render json: @course, status: :created, location: @course }
      else
        format.html { render action: "new" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.json
  def update
    @course = Course.find(params[:id])

    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to courses_url }
      format.json { head :ok }
    end
  end
end

acttest2/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  # GET /lectures
  # GET /lectures.json
  def index
   # @lectures = Lecture.all


    course = Course.find(params[:course_id])
    
    @lectures = Lecture.find_all_by_course_id(course.id)
    
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lectures }
    end
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
    
    
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lecture }
    end
  end

  # GET /lectures/new
  # GET /lectures/new.json
  def new
    @lecture = Lecture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lecture }
    end
  end

  # GET /lectures/1/edit
  def edit
    @lecture = Lecture.find(params[:id])
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(params[:lecture])

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render json: @lecture, status: :created, location: @lecture }
      else
        format.html { render action: "new" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lectures/1
  # PUT /lectures/1.json
  def update
    @lecture = Lecture.find(params[:id])

    respond_to do |format|
      if @lecture.update_attributes(params[:lecture])
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture = Lecture.find(params[:id])
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url }
      format.json { head :ok }
    end
  end
end

acttest2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
end

acttest2/app/helpers/application_helper.rb
module ApplicationHelper
end

acttest2/app/helpers/courses_helper.rb
module CoursesHelper
end

acttest2/app/helpers/lectures_helper.rb
module LecturesHelper
end

acttest2/app/helpers/users_helper.rb
module UsersHelper
end

acttest2/app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% @course.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :instructor %><br />
    <%= f.number_field :instructor %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

acttest2/app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

acttest2/app/views/courses/index.html.erb
<h1>Listing courses</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Instructor</th>
    <th>Price</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @courses.each do |course| %>
  <tr>
	
   	    <td><%= link_to course.name, lectures_path(course_id: course) %></td>
	    <td><%= course.description %></td>
	    <td><%= course.instructor %></td>
	    <td><%= course.price %></td>
	    <td><%= course.status %></td>
	    <td><%= link_to 'Show', course %></td>
	    <td><%= link_to 'Edit', edit_course_path(course) %></td>
	    <td><%= link_to 'Destroy', course, confirm: 'Are you sure?', method: :delet%></td>


  </tr>
<%= course.lectures.count %>

<% end %>

</table>

<br />

<%= link_to 'New Course', new_course_path %>

acttest2/app/views/courses/new.html.erb
<h1>New course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

acttest2/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @course.name %>
</p>

<p>
  <b>Description:</b>
  <%= @course.description %>
</p>

<p>
  <b>Instructor:</b>
  <%= @course.instructor %>
</p>

<p>
  <b>Price:</b>
  <%= @course.price %>
</p>

<p>
  <b>Status:</b>
  <%= @course.status %>
</p>


<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

acttest2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Acttest2</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

acttest2/app/views/lectures/_form.html.erb
<%= form_for(@lecture) do |f| %>
  <% if @lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% @lecture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br />
    <%= f.number_field :course_id %>
  </div>
  <div class="field">
    <%= f.label :video_location %><br />
    <%= f.text_field :video_location %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

acttest2/app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

acttest2/app/views/lectures/index.html.erb
<h1>Listing lectures</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Course</th>
    <th>Video location</th>
    <th>Length</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lectures.each do |lecture| %>
  <tr>
    <td><%= lecture.name %></td>
    <td><%= lecture.description %></td>
    <td><%= lecture.course_id %></td>
    <td><%= lecture.video_location %></td>
    <td><%= lecture.length %></td>
    <td><%= link_to 'Show', lecture %></td>
    <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
    <td><%= link_to 'Destroy', lecture, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lecture', new_lecture_path %>

acttest2/app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render 'form' %>

<%= link_to 'Back', lectures_path %>

acttest2/app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @lecture.name %>
</p>

<p>
  <b>Description:</b>
  <%= @lecture.description %>
</p>

<p>
  <b>Course:</b>
  <%= @lecture.course_id %>
</p>

<p>
  <b>Video location:</b>
  <%= @lecture.video_location %>
</p>

<p>
  <b>Length:</b>
  <%= @lecture.length %>
</p>


<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>